(define-module (petty comparisons)
  #:export (comparisons))

(define comparisons (make-hash-table))

(hash-set! comparisons 'equal "e")
(hash-set! comparisons 'not-equal "ne")
(hash-set! comparisons 'zero "z")
(hash-set! comparisons 'not-zero "nz")
(hash-set! comparisons 'greater "g")
(hash-set! comparisons 'not-greater "ng")
(hash-set! comparisons 'greater-equal "ge")
(hash-set! comparisons 'not-greater-equal "nge")
(hash-set! comparisons 'less "l")
(hash-set! comparisons 'not-less "nl")
(hash-set! comparisons 'less-equal "le")
(hash-set! comparisons 'not-less-equal "nle")
(hash-set! comparisons 'carry "c")
(hash-set! comparisons 'not-carry "nc")
(hash-set! comparisons 'overflow "o")
(hash-set! comparisons 'not-overflow "no")
